version: '3'

services:

  walk-through-db:
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
      - 27017:27017
    networks:
    - walkthrough

  walk-through-app:
    build: .
    ports:
    - 3000:3000
    volumes:
    - .:/usr/local/bin/app
    working_dir: /usr/local/bin/app
    networks:
    - walkthrough
    depends_on:
    - walk-through-db

networks:
  walkthrough: